stages:
  - lint
  - test

image: node:16-alpine

cache:
  key:
    files:
      - frontend/package-lock.json
  paths:
    - frontend/.npm/

before_script:
  - cd frontend
  - npm ci --cache .npm --prefer-offline

Lint frontend:
  stage: lint
  script:
    - npm run lint
  tags:
    - clear-stump

Test frontend:
  stage: test
  script:
    - npm run test
  tags:
    - clear-stump
