name: frontend:lint_and_test

on: [ push ]

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '18' ]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: yarn install --inline-builds
      - name: Run linter
        run: yarn lint
      - name: Run test
        run: yarn test
